# Generated by Django 4.2.7 on 2023-12-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraineerbookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='buy_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
