# Generated by Django 4.2.7 on 2023-12-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraineerbookApp', '0002_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(null=True, upload_to='assets'),
        ),
    ]
