# Generated by Django 4.2.7 on 2023-12-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraineerbookApp', '0004_rename_description_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(null=True, upload_to='backend\\static\\images'),
        ),
    ]
