# Generated by Django 4.2.7 on 2023-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraineerbookApp', '0006_alter_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default='Descripcion de la actividad'),
        ),
    ]
