/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PageView: typeof import('./../../src/components/View/PageView.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QHeader: typeof import('quasar')['QHeader']
    QLayout: typeof import('quasar')['QLayout']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RootView: typeof import('./../../src/components/View/RootView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuspenseView: typeof import('./../../src/components/View/SuspenseView.vue')['default']
    TransitionView: typeof import('./../../src/components/View/TransitionView.vue')['default']
  }
}
