/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Botones: typeof import('./../../src/components/View/clase/botones.vue')['default']
    Carrito: typeof import('./../../src/components/View/clase/carrito.vue')['default']
    ComprarYa: typeof import('./../../src/components/View/clase/comprarYa.vue')['default']
    Descripcion: typeof import('./../../src/components/View/clase/descripcion.vue')['default']
    Horario: typeof import('./../../src/components/View/clase/horario.vue')['default']
    Imagen: typeof import('./../../src/components/View/clase/imagen.vue')['default']
    IMdiCart: typeof import('~icons/mdi/cart')['default']
    PageView: typeof import('./../../src/components/View/PageView.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QBtn: typeof import('quasar')['QBtn']
    QBtnGroup: typeof import('quasar')['QBtnGroup']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QHeader: typeof import('quasar')['QHeader']
    QImg: typeof import('quasar')['QImg']
    QLayout: typeof import('quasar')['QLayout']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QSeparator: typeof import('quasar')['QSeparator']
    QTable: typeof import('quasar')['QTable']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RootView: typeof import('./../../src/components/View/RootView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuspenseView: typeof import('./../../src/components/View/SuspenseView.vue')['default']
    Tabla: typeof import('./../../src/components/View/clase/tabla.vue')['default']
    TransitionView: typeof import('./../../src/components/View/TransitionView.vue')['default']
  }
}
