/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CarritoHeader: typeof import('./../../src/components/layout/CarritoHeader.vue')['default']
    ComentariosActividad: typeof import('./../../src/components/pages/clase/ComentariosActividad.vue')['default']
    DescripcionActividad: typeof import('./../../src/components/pages/clase/DescripcionActividad.vue')['default']
    FooterDatosEmpresa: typeof import('./../../src/components/pages/about/footerDatosEmpresa.vue')['default']
    IFluentPerson28Filled: typeof import('~icons/fluent/person28-filled')['default']
    ImagenActividad: typeof import('./../../src/components/pages/clase/ImagenActividad.vue')['default']
    ImagenDatosEmpresa: typeof import('./../../src/components/pages/about/imagenDatosEmpresa.vue')['default']
    IMdiCart: typeof import('~icons/mdi/cart')['default']
    IMdiLocation: typeof import('~icons/mdi/location')['default']
    IMdiPhone: typeof import('~icons/mdi/phone')['default']
    PageView: typeof import('./../../src/components/View/PageView.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QBadge: typeof import('quasar')['QBadge']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QChatMessage: typeof import('quasar')['QChatMessage']
    QCheckbox: typeof import('quasar')['QCheckbox']
    QForm: typeof import('quasar')['QForm']
    QHeader: typeof import('quasar')['QHeader']
    QImg: typeof import('quasar')['QImg']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QItemSection: typeof import('quasar')['QItemSection']
    QLayout: typeof import('quasar')['QLayout']
    QList: typeof import('quasar')['QList']
    QMenu: typeof import('quasar')['QMenu']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QParallax: typeof import('quasar')['QParallax']
    QSeparator: typeof import('quasar')['QSeparator']
    QTable: typeof import('quasar')['QTable']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RootView: typeof import('./../../src/components/View/RootView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuspenseView: typeof import('./../../src/components/View/SuspenseView.vue')['default']
    TablaActividad: typeof import('./../../src/components/pages/clase/TablaActividad.vue')['default']
    Texto: typeof import('./../../src/components/pages/about/texto.vue')['default']
    TransitionView: typeof import('./../../src/components/View/TransitionView.vue')['default']
    UserAvatar: typeof import('./../../src/components/layout/UserAvatar.vue')['default']
  }
}
